add: tmpapi
mahiro72/go-mvc-server pull request #1
Opened 2023-02-02 15:49 UTC by mahiro72

2023-02-03 17:08 UTC, mahiro72 commented
### 動作確認について

docker環境の立ち上げ

```
make up
```

____

#### GET /users/{id}

```sh
$ curl --location --request GET 'localhost:8080/users/1'
```

response
```json
{
    "id": 1,
    "name": "hoge1"
}
```

<br />

#### POST /users

```sh
$ curl --location --request POST 'localhost:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name":"hoge"
}'
```

response
```json
{
    "id": 4,
    "name": "hoge"
}
```

2023-02-06 07:02 UTC, mokoshin0720 requested changes
大枠の設計はとても良い感じです！
細かい命名やバリデーション部分についてコメントしたので、ご確認をお願い致します！

2023-02-06 07:02 UTC, mokoshin0720 commented on README.md
> +## Getting Started
Readmeめっちゃ丁寧で良いですね👍

2023-02-06 07:02 UTC, mokoshin0720 commented on app/pkg/controller/user.go
> +	idParam, err := strconv.Atoi(idParamString)
15, 16行目は1つにまとめられそうですかね？
変数はなるべく少ない方が実装を追いやすくなる(今後`idParamString`はどこで使われるんだろう？を考えなくて済む)と思うので、まとめられそうならまとめた方が良いかと🙆🏻‍♂️
```
id, err := strconv.Atoi(chi.URLParam(r, "id"))
```

2023-02-06 07:02 UTC, mokoshin0720 commented on app/pkg/model/user.go
> +	Id   int
細かい部分ですが、goでは`ID`のようにどちらも大文字で表現することが多いです！

2023-02-06 07:02 UTC, mokoshin0720 commented on app/pkg/view/user.go
> +	Id   int    `json:"id"`
`ID`こちらもですかね、、！

2023-02-06 07:02 UTC, mokoshin0720 commented on app/pkg/view/user.go
> +type UserJSON struct {
`view`パッケージ内では、（今回の場合）jsonしか扱わないと思うので変数名は`User`とシンプルでも良いかなと思いました！

2023-02-06 07:02 UTC, mokoshin0720 commented on app/pkg/controller/user.go
> +	var j view.UserJSON
細かい部分ですが、リクエストで送られてきたNameが空でないかのチェックなどを入れられると、安全になってなお良いかなと思います！

2023-02-06 15:10 UTC, mahiro72 commented on app/pkg/controller/user.go
> +	idParam, err := strconv.Atoi(idParamString)
確かにおっしゃる通りですね！
確認ありがとうございます🙇

2023-02-06 15:32 UTC, mahiro72 commented on app/pkg/view/user.go
> +type UserJSON struct {
確かにそちらの方がシンプルでわかりやすいですね...！
ご指摘いただきありがとうございます！

2023-02-06 15:37 UTC, mahiro72 commented on README.md
> +## Getting Started
ありがとうございます！！

2023-02-06 15:38 UTC, mahiro72 commented on app/pkg/controller/user.go
> +	idParam, err := strconv.Atoi(idParamString)
[idParamStringの削除](https://github.com/mahiro72/go-mvc-server/pull/1/commits/d19204f143213b11de73a0f047eebad0e3c862e8)

こちらのコミットで修正しました

2023-02-06 15:38 UTC, mahiro72 commented on app/pkg/model/user.go
> +	Id   int
[fix: Id->ID](https://github.com/mahiro72/go-mvc-server/pull/1/commits/841f0cc9f78249942e81d98bc0857bf72ceff3cd)

こちらのコミットで修正しました

2023-02-06 15:39 UTC, mahiro72 commented on app/pkg/view/user.go
> +type UserJSON struct {
[del: JSON](https://github.com/mahiro72/go-mvc-server/pull/1/commits/a3f1b54daacf93039aa3e88a7e65e6162fcaa8a6)

こちらのコミットで修正しました！

2023-02-06 15:39 UTC, mahiro72 commented on app/pkg/controller/user.go
> +	var j view.UserJSON
確かにおっしゃる通りです！

こちらのコミットで修正しました
[add: nameがemptyか確認する処理の追加”](https://github.com/mahiro72/go-mvc-server/pull/1/commits/4d42c81454109905f2c6a79c40512c5b7cb645af)

2023-02-09 07:56 UTC, mokoshin0720 approved these changes
コードの流れとしてはLGTMです！実装お疲れさまでした🥳

最後にコメントした部分は、他の実装者がコードを追いやすくなるという点で意外と重要だったりすると思うので、意識してみてもらえればと思います🙆🏻‍♂️

2023-02-09 07:56 UTC, mokoshin0720 commented on app/pkg/controller/user.go
> +func GetUser(w http.ResponseWriter, r *http.Request) {
この辺は好みもあるのですが、ある程度のまとまりで改行を入れていただけるとコードが見やすくなるかなと思います！
Goの場合だと、エラーハンドリングをした後(ex: 19, 24, 29行目)に改行を入れることが多いですね🙆🏻‍♂️

2023-02-10 08:31 UTC, merged